language: python
python:
  - "2.7"
 
env:
  global:
     - PYTHONPATH="/home/travis/build/adeschen/mpileupTools"

install:
  - pip install codecov
  - pip install pytest-cov

script:
  - py.test --cov-config .coveragerc --cov=./ 

after_success:
  - codecov
